---
- name: Install net-tools (RedHat).
  ansible.builtin.package:
    name: net-tools
    state: present
    enablerepo: epel
  when: ansible_os_family == 'RedHat'

- name: Install net-tools (Debian).
  ansible.builtin.package:
    name: net-tools
    state: present
  when: ansible_os_family == 'Debian'
